version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Mappe le port du container au port local
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Mappe le port NGINX au port local pour le client
    environment:
      - NODE_ENV=production
